name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download and Setup Tweego
        run: |
          wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          unzip -o tweego-2.1.1-linux-x64.zip   # -o = overwrite without asking
          chmod +x tweego
          # Add tweego to the path so npm scripts can find it
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Install Dependencies
        run: npm install

      - name: Build Game
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Make sure GitHub Pages is enabled for the gh-pages branch
