name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download and Setup Tweego
        run: |
          wget https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          unzip -o tweego-2.1.1-linux-x64.zip
          chmod +x tweego
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Download SugarCube 2.36.1
        run: |
          mkdir -p storyformats
          wget https://github.com/tmedwards/sugarcube-2/releases/download/v2.36.1/sugarcube-2.36.1-for-tweego.zip
          unzip -o sugarcube-2.36.1-for-tweego.zip -d storyformats/

      - name: Install Dependencies
        run: npm install

      - name: Build Game
        run: |
          mkdir -p dist
          ./tweego -o dist/index.html -f sugarcube-2:2.36.1 -p storyformats Between_FracturedPromises/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
